# 创建用户
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: myproj
---
# 创建角色
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: myproj
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
# 用户绑定角色
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-reader
  namespace: myproj
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: myproj