apiVersion: v1
kind: Secret
metadata:
  name: consul
  namespace: myproj
data:
  gossip-encryption-key: K1VFM1ZSd2JzSHZLNE5wUitoeDgyZz09
  ca.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoakNDQW02Z0F3SUJBZ0lVVjJYNk53N1Z1
    MC9VUG9BVUk5cWVqZVZaZCtnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NURUxNQWtHQTFVRUJoTUNR
    MDR4Q3pBSkJnTlZCQWdUQW1ka01Rc3dDUVlEVlFRSEV3SnplakVUTUJFRwpBMVVFQ2hNS1MzVmla
    WEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1Ua3dOakF6TURJeU16QXdXaGNOCk1qUXdO
    akF4TURJeU16QXdXakJKTVFzd0NRWURWUVFHRXdKRFRqRUxNQWtHQTFVRUNCTUNaMlF4Q3pBSkJn
    TlYKQkFjVEFuTjZNUk13RVFZRFZRUUtFd3BMZFdKbGNtNWxkR1Z6TVFzd0NRWURWUVFMRXdKRFFU
    Q0NBU0l3RFFZSgpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMK3dKb3hzTXhTV2JT
    dWxEdi9UVlRTQzNqRkFZd0d1CmxySHR4WFU3VXRnWUtmNk9oQnF2MWdQVXZ3TG1DS1pGNkVZemF5
    ZWhWTkV5N0ZRNDdSUVZCUFpMaXhzVFc2dUoKVVpaSWN5YStORHMrc3lkTTJmOWVwNUZZUnl1dm5O
    UTY4NU8yMk1DUHVSUVZqTS9zTnByNkRKNUZYUkxkbGpLNgpCSEtqNnRuT01IMU1zTDh2dmRZa3Bw
    MERuajhZWHNFamhleEQxcy9yRGk4ak5LemJQQTlxOFhFYVNOMGdpUmZFCmlCYTJ5RTJnb0VTenRV
    cCtBaTBRWWZmYzFHem5pN3Y0aFdrOS9JV2tKWGVPUitUNllUVDF0VUhaRXNWajZsVXIKdUxuZzNH
    clhtN2JBNXFlc01QK1ltUDFjQ2duUkRiT3NXYzFwdW92ZVpRbGdlendPZVM0OWJyTUNBd0VBQWFO
    bQpNR1F3RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUl3SFFZ
    RFZSME9CQllFCkZKSjRaZHpROGNrNmZUTnJIdEpEQTdHT3U4L1BNQjhHQTFVZEl3UVlNQmFBRkpK
    NFpkelE4Y2s2ZlROckh0SkQKQTdHT3U4L1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFrOTZV
    MVZUNVpVem4rdzdJMHhzKzVTaGdlSG9JVwpnS0RZbjVKZVplNE9MeStKRGp1Y1ptcFRKeThuNU5n
    NVdxaGVqZmZRSzJEQW1PQ1lTaklSL3YvVTRFNjR6emJUCkJqNFgxR05Xd1Nwdm1hbVNMaS9MU01r
    RmFVTEptUVZhdVBsM0JTOU5Sb3FzNmRlQ21ZNTFibThMZ3RTalZZcXoKeWdseHd4SDI4VllGR3lS
    NGY5K0h0OXVPbmZBOVFvOFlOakMrbDNUMGd2UFVjc3lyMWZOT2RVOG1WWHBmUW1UOQpkM0grbExx
    bk8vOWUvd2VBN3dvQzNONFFJMEpFWXdhZ3YzRzVmVmZQSzJ4SnIxcGdkSWNNQzVYQnUrQldsN21T
    ClkvdlRUVllRL0ExdmFwcHR6dlhyVlBLNDA4Rzk5NGozTWRhOHJhQjV6YkNJMkkrRGYrQlU1K21Z
    Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

  consul.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3ekNDQXRlZ0F3SUJBZ0lVYmpqSHE5Ym93
    a2lEMnVzd2d4YmUzWi9jZDlvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NURUxNQWtHQTFVRUJoTUNR
    MDR4Q3pBSkJnTlZCQWdUQW1ka01Rc3dDUVlEVlFRSEV3SnplakVUTUJFRwpBMVVFQ2hNS1MzVmla
    WEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1Ua3dOakF6TURJeU16QXdXaGNOCk1qQXdO
    akF5TURJeU16QXdXakJzTVFzd0NRWURWUVFHRXdKRFRqRUxNQWtHQTFVRUNCTUNaMlF4Q3pBSkJn
    TlYKQkFjVEFuTjZNUTh3RFFZRFZRUUtFd1ptZFhKdmJtY3hEekFOQmdOVkJBc1RCa052Ym5OMWJE
    RWhNQjhHQTFVRQpBeE1ZYzJWeWRtVnlMbVJpWWk1amJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJn
    a3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFsdk5mWlZUUmYwSVZOUmYwMDRwV2xX
    SW42N2Q5RmdMOGRQaGViRjdIaTdCQmw0VU4KZlNRaWRRSlRMUmNYbmVqemVnY09CejFsRDVSeTlx
    UWxIM0FOUW9VYjJmZHNHWXk4MnFxYVRoQS9VMHZ2azlScAp1OXhJRHVWb0dNcGY4VlQwNU5vYkd1
    Ti9JU01PbHp6WnVCeFU1UUpHbWQxRnZnWnRKemk0a1k0MVd2TnFDbXp4CnJGVmpVejlySXNuMEF4
    S2swY3A3RUoxUDhvTEUraGtuVC92Mk5qRFAvSTBQYjhIRDc1a3dpem5OMjcwUkNITW8KdkpLK29S
    TGpSdnh5MS9iaFdITE1TVnp1NS9tS2FVOEJNN3BQcFk0UEZXS2g1TEtLQ0xEWHREbm9lQWFja0lE
    WgpQbzE5YWRNUkZlNWtoTDUycFlFOHNlaldrVE5nYnFYU2xqQlkvUUlEQVFBQm80R3JNSUdvTUE0
    R0ExVWREd0VCCi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFV
    SEF3SXdEQVlEVlIwVEFRSC8KQkFJd0FEQWRCZ05WSFE0RUZnUVVJTkF0SXFSd2lWaEFrR042T3RT
    OFFrL1RVZG93SHdZRFZSMGpCQmd3Rm9BVQprbmhsM05EeHlUcDlNMnNlMGtNRHNZNjd6ODh3S1FZ
    RFZSMFJCQ0l3SUlJWWMyVnlkbVZ5TG1SaVlpNWpiSFZ6CmRHVnlMbXh2WTJGc2h3Ui9BQUFCTUEw
    R0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCZW5qMVFwR0h1emZ0Z01oM2YKcVZlSjkxQUF6TURrSFIv
    N3JCc1VvQmh5YmlrRENSc2FHaDZseUhFMGZ0M2dneEpPdUV2T0svbE41RVpERVZ2VApCL2NnemVj
    citJR205aHlVUkFEWnRNT25jWVJPK0ZWRkdWclR4VlBQYnRJZVBWOG1qMEo0Yk45WUtYZUFvWUlt
    CmhmMlorVXhMUUZnR3RtMmplQUNpVlZRTFdCVkV5dEkyMEhZY1hLZVR5bDNsbXEwemd3czRRTFp0
    ckxPRVllSFUKbVhIV1VmNU1kaXdrc2hiajU0bE9qU0lpRHBCZnowaDVXOU1qMkpDTVBUMnN6Zm4y
    R2hEbFJGVGRjMGNQeGo2bgpwajhhbWJpaFNuaGRERVp1Z01Jcy9KeXVHQjZpeVZrRzNWZ0dwdEh6
    VUhoUHZKaUpjVnR5NDFDZTdXbmJVY2xOCnU4bnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

  consul-key.pem: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBbHZOZlpWVFJm
    MElWTlJmMDA0cFdsV0luNjdkOUZnTDhkUGhlYkY3SGk3QkJsNFVOCmZTUWlkUUpUTFJjWG5lanpl
    Z2NPQnoxbEQ1Unk5cVFsSDNBTlFvVWIyZmRzR1l5ODJxcWFUaEEvVTB2dms5UnAKdTl4SUR1Vm9H
    TXBmOFZUMDVOb2JHdU4vSVNNT2x6elp1QnhVNVFKR21kMUZ2Z1p0SnppNGtZNDFXdk5xQ216eApy
    RlZqVXo5cklzbjBBeEtrMGNwN0VKMVA4b0xFK2hrblQvdjJOakRQL0kwUGI4SEQ3NWt3aXpuTjI3
    MFJDSE1vCnZKSytvUkxqUnZ4eTEvYmhXSExNU1Z6dTUvbUthVThCTTdwUHBZNFBGV0toNUxLS0NM
    RFh0RG5vZUFhY2tJRFoKUG8xOWFkTVJGZTVraEw1MnBZRThzZWpXa1ROZ2JxWFNsakJZL1FJREFR
    QUJBb0lCQVFDTEpndnhRQS9peklyNgpKM3hEcU1tSjZUSzlvcWFITFBlRjZCSTZ1ZUFlajdyWEx3
    cXhLaWN0VDVoVy8ydUE0R1haUGptYlNPZ3BSWUg0CmhIWElGaVhUQlJzWWdYRS8yREdiTFJzVERQ
    MGpEdVBwbFN4bXhYZ1RhenZiWm1xczc5RFVTWTRrNmtPZHkxQSsKOEJRUEdPYlZPSlRXYjFoRUJH
    Nklja3dKdVZyTDNCNlIyRFZtNTFnQXRmR3ppZ3RiTUNnRmJSRlV2TWRzZXFQdgpDaDFob3gvL3NV
    MlN3eXgwNVE1Q3R4TmMxYy9SRlVTVHNVUFlyaUxQcUxjbHo3cVgwVUVrZnhzeXJXM2FYMHB3ClNP
    ejFRbUgzQlBNTXVESWt6SDBjUlg0YXJsKzA2ZFc0VXcvcEM0UWZsWk4xK29waDRiTmNqd21LMk5k
    cUV3SlQKZElkb0xFWE5Bb0dCQU1GY1pZZEFZa3pPdVNIZGI1VC8wdWF1dDM0MmdCNU9NZ2kzZDZF
    K1R1TjAyK0NCV1NOZApiVWtxNCtNc055bDJWcnIydHBkWDhrR3F2UGxTS0hjS1dHK2QwSnQyWFp6
    RHpiRi9USk1CK2dzL2tlMmQwZG9qCm5JOWRhb2lBZUFCeHJ3Z2VGZEE0ZVUreVRteUxVTFZMbDRU
    eDB3MkRkWHEwZ3E5Y1ZZMnpxV2F6QW9HQkFNZloKMnFkcWJ3RnFLYzRvSlIrSXNzZ00zNkJDWG1a
    ZEhNY1ZqblVaVXBaV3VrM0ZBaWJjeEE1MWVuQlZ5ZTNRd0k3bwpNbkxaYzFra3Z5Y3FMK29YcGc4
    b1MzTk9wME50OW1SZk9jTStrRlRtMStWRlF0dUZycEptOUlQK0FMUlZwUVI1CkY5UzZjMHdJRU5j
    V2xzakhIdVZuVDM0anBjbkhaakx4MVcveWxabVBBb0dCQUpPdUJBVW0wVzBrUGhWMVVIR1cKYWZl
    eDNZZFNETXdZb1BJelhmVVM1NkdsY1FHcENQR1B1NVkwWWRUeHdqZXlvRTh2ZXdsZ0xEQ25QS21Y
    YkR4dQo5RmhiU2laU1l2RUdReVdidWxwVkdpcFpKUlU4Z2poL0ZtWVF6UHJ3VTdiVEhRR3dLS3pk
    VlJuZmJ6Skx2UnFhClgyRTBhU05iRWZEanlTUXgrMDI4dUZjdEFvR0JBSzBYbVBQTGtWMU9UK3NJ
    aGk2cnZQemJlWXhhTDF6RlpMbGgKaUVNUHJhSWNkN3dIMS9kRTJtSVRpZnBsczBGUXZwYUhzYm9i
    Y0haVEIyU3FlMWxySmg2V3JkS3UydHZpRDdlYgphbklhYS9POUJGekZBa1VUb2NHWGZrd2I0UXhQ
    NlY3WWFyV0t6M1dZdnMwcitXam9YWEFmYkpBNTI4dko4bEJKCmVLMC9GQ2N0QW9HQkFKY1I5M2lD
    ZGhVME8xSUVreWkwSTJGQVl2Qmg2KzFINkJZWGp1MXdXZ3J1VEFGZk5mM2cKVnQ1SXBrb0Nwa2k5
    YjVBc280b2hIOHAzdjBXS3dLbjhTNEZPRDRuUWpjQituY3Z2eFhzcldQRll4cWpNZW5mSwpTVFFa
    SXJPQ0cxenZTcHlwOEZBT3lKbURodW1xSE01eXUrcjRUTFNMK2c5NVhwcm9na3ZMRGFkcQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul
  namespace: myproj
data:
  server.json: |
    {
      "bind_addr": "0.0.0.0",
      "ca_file": "/etc/tls/ca.pem",
      "cert_file": "/etc/tls/consul.pem",
      "client_addr": "0.0.0.0",
      "disable_host_node_id": true,
      "data_dir": "/consul/data",
      "datacenter": "myproj",
      "domain": "cluster.local",
      "key_file": "/etc/tls/consul-key.pem",
      "ports": {
        "https": 8443
      },
      "retry_join": [
        "provider=k8s namespace=myproj label_selector=\"app=consul,component=server\""
      ],
      "server": true,
      "telemetry": {
        "prometheus_retention_time": "5m"
      },
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ui": true
    }
  client.json: |
    {
      "bind_addr": "0.0.0.0",
      "ca_file": "/etc/tls/ca.pem",
      "cert_file": "/etc/tls/consul.pem",
      "client_addr": "0.0.0.0",
      "disable_host_node_id": true,
      "data_dir": "/consul/data",
      "datacenter": "myproj",
      "domain": "cluster.local",
      "key_file": "/etc/tls/consul-key.pem",
      "ports": {
        "https": 8443
      },
      "retry_join": ["consul.myproj.svc.cluster.local"],
      "server": false,
      "telemetry": {
        "prometheus_retention_time": "5m"
      },
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ui": false
    }
